KEY_SIZE = 4096
CRYPTO_EXPONENT = 65537

PRIVATE_KEY_ENCODING = "PEM"
PUBLIC_KEY_ENCODING = "PEM"

BYTE_ENCODING = "utf-8"

LEDGER_PATH = "ledger"
PRIVATE_KEY_FILE_NAME = "key.pem"
PUBLIC_KEY_FILE_NAME = "key.pub"

INITIAL_TRUSTED_IP = "192.168.195.30"

IP = "localhost"
PORT = "1939"

HTTP_CONSTANTS = {
  "SOURCE_IP_HEADER": "source"
}

JSON_CONSTANTS = {
  "PEERS_KEY": "peers",
  "PUBLIC_KEY_KEY": "publicKey"
}
