KEY_SIZE = 4096
CRYPTO_EXPONENT = 65537

ECC_CURVE = "P-256"
ECC_PROTECTION = "PBKDF2WithHMAC-SHA1AndAES128-CBC"

PRIVATE_KEY_ENCODING = "PEM"
PUBLIC_KEY_ENCODING = "PEM"

SIGNATURE_VERIFIER_MODE = "fips-186-3"

BYTE_ENCODING = "utf-8"

LEDGER_PATH = "ledger"
PRIVATE_KEY_FILE_NAME = "key.pem"
PUBLIC_KEY_FILE_NAME = "key.pub"
USER_DATA_FILE_NAME = "user.data"

INITIAL_TRUSTED_IP = "192.168.195.30"
INITIAL_TRUSTED_NAME = "30"

IP = "localhost"
PORT = "1939"

HTTP_CONSTANTS = {
  "SOURCE_IP_HEADER": "source",
  "NAME_HEADER": "name"
}

JSON_CONSTANTS = {
  "PEERS_KEY": "peers",
  "PUBLIC_KEY_KEY": "publicKey",
  "NAME_KEY": "name"
}
